-- Create band events table
CREATE TABLE IF NOT EXISTS band_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    band_name VARCHAR(255) NOT NULL,
    place VARCHAR(255),
    date DATE NOT NULL,
    comment TEXT,
    rating INT NOT NULL CHECK (rating >= 0 AND rating <= 5),
    users_id BIGINT NOT NULL,
    creation_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    modification_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_band_events_user FOREIGN KEY (users_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_users_id ON band_events(users_id);
CREATE INDEX IF NOT EXISTS idx_date ON band_events(date);
CREATE INDEX IF NOT EXISTS idx_rating ON band_events(rating);