name: Version Tagging

on:
  workflow_call:
    inputs:
      component:
        required: true
        type: string
        description: "Component name (backend or frontend)"
    outputs:
      new_version:
        description: "New version tag"
        value: ${{ jobs.tag.outputs.new_version }}
    permissions:
      contents: write

jobs:
  tag:
    name: Determine Version and Tag
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      new_version: ${{ steps.increment_version.outputs.new_version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Determine latest tag
        id: get_latest_tag
        run: |
          latest_tag=$(git tag -l 'v*' | sort -rV | head -n 1 || echo "v0")
          echo "Latest tag: $latest_tag"
          echo "latest_tag=$latest_tag" >> $GITHUB_ENV

      - name: Increment version
        id: increment_version
        run: |
          latest_tag="${{ env.latest_tag }}"
          if [[ $latest_tag =~ ^v([0-9]+)$ ]]; then
            version_number=${BASH_REMATCH[1]}
            new_version_number=$((version_number + 1))
            new_version="v$new_version_number"
          else
            new_version="v1"  # Default to v1 if no valid tag is found
          fi
          echo "New version: $new_version"
          echo "new_version=$new_version" >> $GITHUB_OUTPUT

      - name: Tag new version
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git tag ${{ steps.increment_version.outputs.new_version }}
          git push origin ${{ steps.increment_version.outputs.new_version }}